### ISSUE TITLE
Add license from original Maxim code

### ISSUE THREAD

**Issue by sandyjmacdonald** [pimoroni/max30105-python#1]
https://github.com/sparkfun/SparkFun_MAX3010x_Sensor_Library/blob/master/examples/Example5_HeartRate/License.ino

**Comment by Gadgetoid** [comment]
Honestly, I'm not sure this is even relevant. We have neither a copy or, nor a substantial portion of their code, but a re-implementation in Python and our license is already compatible. Yes it's a derived work, but we're not holding it to random or doing anything naughty with it. Maybe just a code comment referencing the source material would suffice?
